# Generated by Django 2.2.5 on 2019-12-20 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storys', '0003_auto_20191211_1940'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AdvUser',
        ),
    ]
