# Generated by Django 2.2.5 on 2020-01-06 14:34

from django.db import migrations
import easy_thumbnails.fields


class Migration(migrations.Migration):

    dependencies = [
        ('storys', '0005_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='img',
            name='img',
            field=easy_thumbnails.fields.ThumbnailerImageField(upload_to=''),
        ),
    ]
